2021-05-11 22:20:09,112 INFO    MainThread:8134 [wandb_setup.py:_flush():69] setting env: {}
2021-05-11 22:20:09,112 INFO    MainThread:8134 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-11 22:20:09,113 INFO    MainThread:8134 [wandb_init.py:_log_setup():336] Logging user logs to /home/pi/FedML-IoT/raspberry_pi/fedopt/wandb/run-20210511_222009-vt4s6wnm/logs/debug.log
2021-05-11 22:20:09,113 INFO    MainThread:8134 [wandb_init.py:_log_setup():337] Logging internal logs to /home/pi/FedML-IoT/raspberry_pi/fedopt/wandb/run-20210511_222009-vt4s6wnm/logs/debug-internal.log
2021-05-11 22:20:09,114 INFO    MainThread:8134 [wandb_init.py:init():369] calling init triggers
2021-05-11 22:20:09,114 INFO    MainThread:8134 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'dataset': 'mnist', 'data_dir': '"./../../../data/mnist"', 'partition_method': 'hetero', 'partition_alpha': 0.5, 'model': 'lr', 'client_num_per_round': 2, 'comm_round': 200, 'epochs': 10, 'lr': 0.03, 'wd': 0.001, 'batch_size': 10, 'frequency_of_the_test': 1, 'is_mobile': 1, 'clip': 0.5}
2021-05-11 22:20:09,114 INFO    MainThread:8134 [wandb_init.py:init():418] starting backend
2021-05-11 22:20:09,115 INFO    MainThread:8134 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-11 22:20:09,139 INFO    MainThread:8134 [backend.py:ensure_launched():132] starting backend process...
2021-05-11 22:20:09,153 INFO    MainThread:8134 [backend.py:ensure_launched():137] started backend process with pid: 8154
2021-05-11 22:20:09,157 INFO    MainThread:8134 [wandb_init.py:init():423] backend started and connected
2021-05-11 22:20:09,162 INFO    MainThread:8134 [wandb_init.py:init():465] updated telemetry
2021-05-11 22:20:09,164 INFO    MainThread:8134 [wandb_init.py:init():484] communicating current version
2021-05-11 22:20:11,062 INFO    MainThread:8134 [wandb_init.py:init():489] got version response 
2021-05-11 22:20:11,062 INFO    MainThread:8134 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-11 22:20:11,273 INFO    MainThread:8134 [wandb_init.py:init():522] starting run threads in backend
2021-05-11 22:20:11,365 INFO    MainThread:8134 [wandb_run.py:_console_start():1565] atexit reg
2021-05-11 22:20:11,366 INFO    MainThread:8134 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-11 22:20:11,367 INFO    MainThread:8134 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-11 22:20:11,371 INFO    MainThread:8134 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-11 22:20:11,371 INFO    MainThread:8134 [wandb_init.py:init():546] run started, returning control to user process
2021-05-11 22:21:29,806 INFO    MainThread:8134 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-11 22:21:29,807 INFO    MainThread:8134 [wandb_run.py:_restore():1507] restore
2021-05-11 22:21:31,830 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 770
  total_bytes: 770
}

2021-05-11 22:21:31,946 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 770
  total_bytes: 770
}

2021-05-11 22:21:32,168 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 770
  total_bytes: 770
}

2021-05-11 22:21:32,324 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 770
  total_bytes: 4406
}

2021-05-11 22:21:32,847 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4406
  total_bytes: 4406
}

2021-05-11 22:21:32,954 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4406
  total_bytes: 4406
}

2021-05-11 22:21:33,063 INFO    MainThread:8134 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4406
  total_bytes: 4406
}

2021-05-11 22:21:34,348 INFO    MainThread:8134 [wandb_run.py:_show_files():1879] logging synced files
